services:
  - type: web
    name: protspace
    runtime: python
    repo: https://github.com/tsenoner/ProtSpace
    plan: free
    # envVars:
    #   - key: PYTHON_VERSION
    #     sync: false
    region: frankfurt
    buildCommand: poetry install --no-dev
    startCommand: poetry run gunicorn protspace.wsgi:server --bind 0.0.0.0 #:$PORT
# version: "1"
