#!/usr/bin/env python
"""Write the web app's example bundle manifest from the bundle files themselves.

The manifest is ``apps/web/src/explore/example-manifest.ts``, a generated
TypeScript module. The Import-menu catalog
(``apps/web/src/explore/example-datasets.ts``) derives each example's URL, size
and label numbers from it; a unit test checks every curated ``defaultView``
against the ``columns`` and ``projections`` recorded here; and
``pnpm examples:fetch``, which the deploy runs, verifies every served file
against its byte count and sha256. Every value is read from the file, never
typed by hand, so none of those checks can drift from the bytes that ship.

Each example is hosted either in the repository (``--repo``: the startup demo,
served from ``apps/web/public/<file>``) or as an asset of a versioned GitHub
release (``--release``: served from ``examples/<file>`` once the deploy has
downloaded it). Provenance (ProtSpace version, git SHA, UniProt releases, build
command, build time, Zenodo DOI) comes from the key/value metadata that the
showcase build writes onto a bundle's annotations table; a bundle without it
records ``null``.

The script needs only pyarrow, so it runs outside the protspace environment::

    uv run --no-project --with pyarrow python \\
        apps/protspace/scripts/generate_examples/write_manifest.py \\
        --repo demo=apps/web/public/data.parquetbundle \\
        --release swissprot=staging/swissprot_2026_03.parquetbundle \\
        --release-tag showcase-2026_03 --retain-previous

``--refresh`` re-reads the files of the examples already in the manifest
(repo-hosted ones from ``apps/web/public/``, release-hosted ones from
``--examples-dir``, e.g. after ``pnpm examples:fetch``), and ``--check``
compares instead of writing, exiting 1 when the committed manifest is stale.
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import sys
from collections.abc import Iterable
from pathlib import Path

import pyarrow.parquet as pq

REPO_ROOT = Path(__file__).resolve().parents[4]
DEFAULT_OUT = REPO_ROOT / "apps/web/src/explore/example-manifest.ts"
PUBLIC_DIR = REPO_ROOT / "apps/web/public"
DEFAULT_EXAMPLES_DIR = PUBLIC_DIR / "examples"

DELIMITER = b"---PARQUET_DELIMITER---"

# Mirrors the web reader (packages/core/src/components/data-loader/utils/conversion.ts):
# the protein-id column is the first of these present, else the first column, and
# none of ID_COLUMNS is ever an annotation.
ID_CANDIDATES = ("identifier", "protein_id", "id", "protein", "uniprot")
ID_COLUMNS = frozenset(
    {
        "projection_name",
        "x",
        "y",
        "z",
        "identifier",
        "protein_id",
        "id",
        "uniprot",
        "entry",
    }
)

# Provenance keys on the annotations table's Parquet key/value metadata.
META_EXAMPLE_ID = "example_id"
META_PROTSPACE_VERSION = "protspace_version"
META_GIT_SHA = "git_sha"
META_MEMBERSHIP_RELEASE = "membership_release"
# A JSON object mapping a column group to the release its values come from
# (e.g. {"uniprot": "2026_03", "eat": "2026_02"}), or a single release string.
META_UNIPROT_RELEASE = "uniprot_release"
META_BUILT_AT = "built_at"
META_COMMAND = "command"
META_ZENODO_DOI = "zenodo_doi"

HEADER = """\
// GENERATED by apps/protspace/scripts/generate_examples/write_manifest.py; do not edit.
// Every value below is read from the bundle file it describes. To change it, rebuild
// the bundle and rerun the writer (its docstring shows how).

/** Where a bundle's file is served from and what it holds. */
interface ExampleBundleRecord {
  /** Path under `apps/web/public/` for `'repo'`; the release asset name for `'release'`. */
  readonly file: string;
  /** `'repo'`: committed under `apps/web/public/`. `'release'`: an asset of `release`, deployed under `examples/`. */
  readonly hosting: 'repo' | 'release';
  /** Decoded file size in bytes (download progress is measured against it). */
  readonly bytes: number;
  readonly sha256: string;
  readonly proteins: number;
  /** Annotation columns, in file order, without the protein-id column. */
  readonly columns: readonly string[];
  /** Projection names, in file order. */
  readonly projections: readonly string[];
  readonly releases: {
    /** UniProt release the protein set was drawn from. */
    readonly membership: string | null;
    /** Release per annotation column group, e.g. `{ uniprot: '2026_03' }`. */
    readonly annotations: Readonly<Record<string, string>>;
  };
  readonly protspaceVersion: string | null;
  readonly gitSha: string | null;
  readonly command: string | null;
  readonly builtAt: string | null;
  readonly zenodoDoi: string | null;
}

/** A file of the previous release, still deployed for one cycle so open tabs and old links keep working. */
interface RetainedBundle {
  readonly release: string;
  readonly file: string;
  readonly bytes: number;
  readonly sha256: string;
}

interface ExampleManifest {
  /** The GitHub release the `'release'`-hosted files come from; `null` while every file is in the repository. */
  readonly release: string | null;
  readonly retained: readonly RetainedBundle[];
  readonly examples: Readonly<Record<string, ExampleBundleRecord>>;
}

"""
OPEN_LINE = "export const EXAMPLE_MANIFEST: ExampleManifest = {"
CLOSE_LINE = "};"


def split_bundle(data: bytes) -> list[bytes]:
    parts = data.split(DELIMITER)
    if not 3 <= len(parts) <= 5:
        raise ValueError(f"expected 3 to 5 bundle parts, found {len(parts)}")
    return parts


def _decode_metadata(raw: dict[bytes, bytes] | None) -> dict[str, str]:
    return {k.decode(): v.decode() for k, v in (raw or {}).items()}


def _annotation_releases(value: str | None) -> dict[str, str]:
    if not value:
        return {}
    try:
        parsed = json.loads(value)
    except json.JSONDecodeError:
        return {"all": value}
    if isinstance(parsed, dict):
        return {str(k): str(v) for k, v in parsed.items()}
    return {"all": str(parsed)}


def _unique_in_order(values: Iterable[object]) -> list[str]:
    seen: dict[str, None] = {}
    for value in values:
        if value is not None:
            seen.setdefault(str(value), None)
    return list(seen)


def read_bundle_record(path: Path, *, example_id: str, file: str, hosting: str) -> dict:
    """The manifest record for one bundle file, read from its bytes."""
    data = path.read_bytes()
    parts = split_bundle(data)
    annotations = pq.read_table(io.BytesIO(parts[0]))
    projections_metadata = pq.read_table(io.BytesIO(parts[1]))

    names = annotations.column_names
    id_column = next((c for c in ID_CANDIDATES if c in names), names[0])
    columns = [c for c in names if c != id_column and c not in ID_COLUMNS]
    proteins = len(set(annotations.column(id_column).to_pylist()))
    projections = (
        _unique_in_order(projections_metadata.column("projection_name").to_pylist())
        if "projection_name" in projections_metadata.column_names
        else []
    )

    meta = _decode_metadata(annotations.schema.metadata)
    stamped_id = meta.get(META_EXAMPLE_ID)
    if stamped_id and stamped_id != example_id:
        raise ValueError(
            f"{path} is stamped example_id={stamped_id!r}, not {example_id!r}"
        )

    return {
        "file": file,
        "hosting": hosting,
        "bytes": len(data),
        "sha256": hashlib.sha256(data).hexdigest(),
        "proteins": proteins,
        "columns": columns,
        "projections": projections,
        "releases": {
            "membership": meta.get(META_MEMBERSHIP_RELEASE),
            "annotations": _annotation_releases(meta.get(META_UNIPROT_RELEASE)),
        },
        "protspaceVersion": meta.get(META_PROTSPACE_VERSION),
        "gitSha": meta.get(META_GIT_SHA),
        "command": meta.get(META_COMMAND),
        "builtAt": meta.get(META_BUILT_AT),
        "zenodoDoi": meta.get(META_ZENODO_DOI),
    }


def render_manifest(manifest: dict) -> str:
    body = json.dumps(manifest, indent=2, ensure_ascii=False)
    # `json.dumps` opens with "{" and closes with "}"; swap in the TS lines.
    inner = body[1:-1].strip("\n")
    return f"{HEADER}{OPEN_LINE}\n{inner}\n{CLOSE_LINE}\n"


def parse_manifest(text: str) -> dict:
    """The manifest a previous run wrote (the inverse of :func:`render_manifest`)."""
    lines = text.splitlines()
    try:
        start = lines.index(OPEN_LINE)
        end = lines.index(CLOSE_LINE, start)
    except ValueError as error:
        raise ValueError("not a manifest written by write_manifest.py") from error
    return json.loads("{\n" + "\n".join(lines[start + 1 : end]) + "\n}")


def retained_after(previous: dict | None, new_release: str | None) -> list[dict]:
    """The previous release's files, kept for one cycle when the release changes.

    Files retained by the previous manifest are dropped: a file is kept for
    exactly one release after the one it belonged to.
    """
    if not previous or previous.get("release") in (None, new_release):
        return list(previous.get("retained", [])) if previous else []
    return [
        {
            "release": previous["release"],
            "file": record["file"],
            "bytes": record["bytes"],
            "sha256": record["sha256"],
        }
        for record in previous["examples"].values()
        if record["hosting"] == "release"
    ]


def _parse_pairs(values: list[str], flag: str) -> list[tuple[str, Path]]:
    pairs = []
    for value in values:
        example_id, sep, path = value.partition("=")
        if not sep or not example_id or not path:
            raise SystemExit(f"{flag} expects ID=PATH, got {value!r}")
        pairs.append((example_id, Path(path)))
    return pairs


def _repo_file(path: Path, public_dir: Path) -> str:
    try:
        return path.resolve().relative_to(public_dir.resolve()).as_posix()
    except ValueError as error:
        raise SystemExit(
            f"repo-hosted bundle {path} is not under {public_dir}"
        ) from error


def build_manifest(
    *,
    repo: list[tuple[str, Path]],
    release: list[tuple[str, Path]],
    release_tag: str | None,
    retained: list[dict],
    public_dir: Path = PUBLIC_DIR,
) -> dict:
    if release and not release_tag:
        raise SystemExit("--release needs --release-tag")
    examples: dict[str, dict] = {}
    for example_id, path in repo:
        file = _repo_file(path, public_dir)
        examples[example_id] = read_bundle_record(
            path, example_id=example_id, file=file, hosting="repo"
        )
    for example_id, path in release:
        if example_id in examples:
            raise SystemExit(f"example {example_id!r} is listed twice")
        examples[example_id] = read_bundle_record(
            path, example_id=example_id, file=path.name, hosting="release"
        )
    return {
        "release": release_tag if release else None,
        "retained": retained,
        "examples": examples,
    }


def refresh_manifest(previous: dict, *, public_dir: Path, examples_dir: Path) -> dict:
    """Re-read every example already in the manifest from its file."""
    repo = []
    release = []
    for example_id, record in previous["examples"].items():
        if record["hosting"] == "repo":
            repo.append((example_id, public_dir / record["file"]))
        else:
            release.append((example_id, examples_dir / record["file"]))
    return build_manifest(
        repo=repo,
        release=release,
        release_tag=previous.get("release"),
        retained=list(previous.get("retained", [])),
        public_dir=public_dir,
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument(
        "--repo",
        action="append",
        default=[],
        metavar="ID=PATH",
        help="A repo-hosted example (its file must be under apps/web/public/).",
    )
    parser.add_argument(
        "--release",
        action="append",
        default=[],
        metavar="ID=PATH",
        help="A release-hosted example; the file name becomes the asset name.",
    )
    parser.add_argument(
        "--release-tag", help="The GitHub release holding --release files."
    )
    parser.add_argument(
        "--retain-previous",
        action="store_true",
        help="Keep the current manifest's release files as retained when the release changes.",
    )
    parser.add_argument(
        "--refresh",
        action="store_true",
        help="Re-read the examples already in the manifest instead of taking --repo/--release.",
    )
    parser.add_argument("--examples-dir", type=Path, default=DEFAULT_EXAMPLES_DIR)
    parser.add_argument("--public-dir", type=Path, default=PUBLIC_DIR)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if --out differs instead of writing it.",
    )
    args = parser.parse_args(argv)

    previous = parse_manifest(args.out.read_text()) if args.out.exists() else None
    if args.refresh:
        if previous is None:
            raise SystemExit(f"--refresh needs an existing manifest at {args.out}")
        if args.repo or args.release:
            raise SystemExit(
                "--refresh takes its examples from the manifest, not --repo/--release"
            )
        manifest = refresh_manifest(
            previous, public_dir=args.public_dir, examples_dir=args.examples_dir
        )
    else:
        if not args.repo and not args.release:
            raise SystemExit("name at least one example with --repo or --release")
        new_tag = args.release_tag if args.release else None
        retained = retained_after(previous, new_tag) if args.retain_previous else []
        manifest = build_manifest(
            repo=_parse_pairs(args.repo, "--repo"),
            release=_parse_pairs(args.release, "--release"),
            release_tag=args.release_tag,
            retained=retained,
            public_dir=args.public_dir,
        )

    rendered = render_manifest(manifest)
    if args.check:
        if not args.out.exists() or args.out.read_text() != rendered:
            print(f"{args.out} is stale; rerun write_manifest.py", file=sys.stderr)
            return 1
        print(f"{args.out} is up to date")
        return 0
    args.out.write_text(rendered)
    print(f"wrote {args.out} ({len(manifest['examples'])} examples)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
