// GENERATED by apps/protspace/scripts/generate_examples/write_manifest.py; do not edit.
// Every value below is read from the bundle file it describes. To change it, rebuild
// the bundle and rerun the writer (its docstring shows how).

/** Where a bundle's file is served from and what it holds. */
interface ExampleBundleRecord {
  /** Path under `apps/web/public/` for `'repo'`; the release asset name for `'release'`. */
  readonly file: string;
  /** `'repo'`: committed under `apps/web/public/`. `'release'`: an asset of `release`, deployed under `examples/`. */
  readonly hosting: 'repo' | 'release';
  /** Decoded file size in bytes (download progress is measured against it). */
  readonly bytes: number;
  readonly sha256: string;
  readonly proteins: number;
  /** Annotation columns, in file order, without the protein-id column. */
  readonly columns: readonly string[];
  /** Projection names, in file order. */
  readonly projections: readonly string[];
  /** Whether the bundle carries a statistics part (separation scores, from `protspace stats`). */
  readonly statistics: boolean;
  readonly releases: {
    /** UniProt release the protein set was drawn from. */
    readonly membership: string | null;
    /** Release per annotation column group, e.g. `{ uniprot: '2026_03' }`. */
    readonly annotations: Readonly<Record<string, string>>;
  };
  readonly protspaceVersion: string | null;
  readonly gitSha: string | null;
  readonly command: string | null;
  readonly builtAt: string | null;
  readonly zenodoDoi: string | null;
}

/** A file of the previous release, still deployed for one cycle so open tabs and old links keep working. */
interface RetainedBundle {
  readonly release: string;
  readonly file: string;
  readonly bytes: number;
  readonly sha256: string;
}

interface ExampleManifest {
  /** The GitHub release the `'release'`-hosted files come from; `null` while every file is in the repository. */
  readonly release: string | null;
  readonly retained: readonly RetainedBundle[];
  readonly examples: Readonly<Record<string, ExampleBundleRecord>>;
}

export const EXAMPLE_MANIFEST: ExampleManifest = {
  "release": "showcase-2026_03",
  "retained": [],
  "examples": {
    "demo": {
      "file": "data.parquetbundle",
      "hosting": "repo",
      "bytes": 1039050,
      "sha256": "46f8b364029a75c0fa0761d8c9b7d754227b097383288d56c3a49453b067a117",
      "proteins": 7831,
      "columns": [
        "protein_families",
        "annotation_score",
        "cc_subcellular_location",
        "ec",
        "fragment",
        "go_bp",
        "go_cc",
        "go_mf",
        "keyword",
        "length",
        "protein_existence",
        "reviewed",
        "xref_pdb",
        "root",
        "domain",
        "kingdom",
        "phylum",
        "class",
        "order",
        "family",
        "genus",
        "species",
        "pfam",
        "superfamily",
        "cath",
        "signal_peptide",
        "smart",
        "cdd",
        "panther",
        "prosite",
        "prints",
        "pfam_clan",
        "ted_domains",
        "predicted_subcellular_location",
        "predicted_membrane",
        "predicted_signal_peptide",
        "predicted_transmembrane",
        "gene_name",
        "protein_name",
        "uniprot_kb_id"
      ],
      "projections": [
        "ProtT5 — UMAP 2",
        "ProtT5 — PCA 2",
        "ESM2-650M — UMAP 2",
        "ESM2-650M — PCA 2"
      ],
      "statistics": false,
      "releases": {
        "membership": "2026_01",
        "annotations": {
          "refreshed": "2026_03",
          "source": "2026_01"
        }
      },
      "protspaceVersion": "4.15.0",
      "gitSha": "621ea942223ad487fcb7418022d9a3fd17acaf39",
      "command": "build_showcase.py build --only demo --cli-root $CLI",
      "builtAt": "2026-09-30T16:57:47+00:00",
      "zenodoDoi": null
    },
    "three-finger-toxins": {
      "file": "three-finger-toxins_2026_03.parquetbundle",
      "hosting": "release",
      "bytes": 135572,
      "sha256": "1d237bfc97e4448b76d121e8d5760060532a098f35ae950ffdbce753bb955ec1",
      "proteins": 1089,
      "columns": [
        "toxin_class",
        "toxin_subfamily",
        "eat_split",
        "toxin_class_withheld",
        "toxin_subfamily_withheld",
        "toxin_class_uniprot_rule",
        "species",
        "genus",
        "family",
        "protein_families",
        "reviewed",
        "length",
        "fragment",
        "protein_existence",
        "annotation_score",
        "keyword",
        "xref_pdb",
        "go_bp",
        "go_mf",
        "pfam",
        "signal_peptide",
        "panther",
        "prosite",
        "ted_domains",
        "predicted_subcellular_location",
        "predicted_membrane",
        "predicted_signal_peptide",
        "gene_name",
        "protein_name",
        "uniprot_kb_id",
        "mature_length",
        "toxin_class__pred_value",
        "toxin_class__pred_confidence",
        "toxin_class__pred_source",
        "toxin_subfamily__pred_value",
        "toxin_subfamily__pred_confidence",
        "toxin_subfamily__pred_source",
        "cluster_elbow_ProtT5 — UMAP 2",
        "cluster_silhouette_ProtT5 — UMAP 2",
        "cluster_elbow_ProtT5 — PCA 2",
        "cluster_silhouette_ProtT5 — PCA 2"
      ],
      "projections": [
        "ProtT5 — UMAP 2",
        "ProtT5 — PCA 2"
      ],
      "statistics": true,
      "releases": {
        "membership": "2026_03",
        "annotations": {
          "refreshed": "2026_03",
          "withheld-truth": "2026_03"
        }
      },
      "protspaceVersion": "4.15.0",
      "gitSha": "621ea942223ad487fcb7418022d9a3fd17acaf39",
      "command": "build_showcase.py build --only three-finger-toxins --cli-root $CLI",
      "builtAt": "2026-09-30T16:40:01+00:00",
      "zenodoDoi": null
    },
    "human-fly": {
      "file": "human-fly_2026_03.parquetbundle",
      "hosting": "release",
      "bytes": 22677971,
      "sha256": "8c29273de6c4ba4677236ddfb04087fad4d36cc9637b89557c71c95a081bb38b",
      "proteins": 105562,
      "columns": [
        "species",
        "protein_families",
        "annotation_score",
        "cc_subcellular_location",
        "ec",
        "fragment",
        "go_bp",
        "go_cc",
        "go_mf",
        "keyword",
        "length",
        "protein_existence",
        "reviewed",
        "xref_pdb",
        "root",
        "domain",
        "kingdom",
        "phylum",
        "class",
        "order",
        "family",
        "genus",
        "pfam",
        "superfamily",
        "cath",
        "signal_peptide",
        "smart",
        "cdd",
        "panther",
        "prosite",
        "prints",
        "pfam_clan",
        "ted_domains",
        "gene_name",
        "protein_name",
        "uniprot_kb_id",
        "cluster_elbow_ProtT5 — UMAP 2",
        "cluster_silhouette_ProtT5 — UMAP 2",
        "cluster_elbow_ProtT5 — PCA 2",
        "cluster_silhouette_ProtT5 — PCA 2"
      ],
      "projections": [
        "ProtT5 — UMAP 2",
        "ProtT5 — PCA 2"
      ],
      "statistics": true,
      "releases": {
        "membership": "2025_04",
        "annotations": {
          "refreshed": "2026_03"
        }
      },
      "protspaceVersion": "4.15.0",
      "gitSha": "621ea942223ad487fcb7418022d9a3fd17acaf39",
      "command": "build_showcase.py build --only human-fly --cli-root $CLI",
      "builtAt": "2026-09-30T21:54:33+00:00",
      "zenodoDoi": null
    },
    "beta-lactamase": {
      "file": "beta-lactamase_2026_03.parquetbundle",
      "hosting": "release",
      "bytes": 13194257,
      "sha256": "605b750be5740c5f37b2318bd68cfc3ac507402a609fea571f7ee6f7b581e2ad",
      "proteins": 113015,
      "columns": [
        "protein_families",
        "annotation_score",
        "cc_subcellular_location",
        "ec",
        "fragment",
        "go_bp",
        "go_cc",
        "go_mf",
        "keyword",
        "length",
        "protein_existence",
        "reviewed",
        "xref_pdb",
        "root",
        "domain",
        "kingdom",
        "phylum",
        "class",
        "order",
        "family",
        "genus",
        "species",
        "pfam",
        "superfamily",
        "cath",
        "signal_peptide",
        "smart",
        "cdd",
        "panther",
        "prosite",
        "prints",
        "pfam_clan",
        "ted_domains",
        "gene_name",
        "protein_name",
        "uniprot_kb_id",
        "cluster_elbow_ProtT5 — UMAP 2",
        "cluster_silhouette_ProtT5 — UMAP 2",
        "cluster_elbow_ProtT5 — PCA 2",
        "cluster_silhouette_ProtT5 — PCA 2"
      ],
      "projections": [
        "ProtT5 — UMAP 2",
        "ProtT5 — PCA 2"
      ],
      "statistics": true,
      "releases": {
        "membership": "2026_02",
        "annotations": {
          "refreshed": "2026_03"
        }
      },
      "protspaceVersion": "4.15.0",
      "gitSha": "621ea942223ad487fcb7418022d9a3fd17acaf39",
      "command": "build_showcase.py build --only beta-lactamase --cli-root $CLI",
      "builtAt": "2026-09-30T17:00:16+00:00",
      "zenodoDoi": null
    },
    "swissprot": {
      "file": "swissprot_2026_03.parquetbundle",
      "hosting": "release",
      "bytes": 135853411,
      "sha256": "90e44a8cf13abbdac8e0991686ca95ca0500bdf21238948ba67025db65e211f2",
      "proteins": 573649,
      "columns": [
        "domain",
        "annotation_score",
        "cc_subcellular_location",
        "ec",
        "fragment",
        "go_bp",
        "go_cc",
        "go_mf",
        "keyword",
        "length",
        "protein_existence",
        "protein_families",
        "reviewed",
        "xref_pdb",
        "root",
        "kingdom",
        "phylum",
        "class",
        "order",
        "family",
        "genus",
        "species",
        "pfam",
        "superfamily",
        "cath",
        "signal_peptide",
        "smart",
        "cdd",
        "panther",
        "prosite",
        "prints",
        "pfam_clan",
        "ted_domains",
        "gene_name",
        "protein_name",
        "uniprot_kb_id",
        "cluster_elbow_ProtT5 — UMAP 2",
        "cluster_silhouette_ProtT5 — UMAP 2",
        "cluster_elbow_ProtT5 — PCA 2",
        "cluster_silhouette_ProtT5 — PCA 2"
      ],
      "projections": [
        "ProtT5 — UMAP 2",
        "ProtT5 — PCA 2"
      ],
      "statistics": true,
      "releases": {
        "membership": "2025_04",
        "annotations": {
          "refreshed": "2026_03"
        }
      },
      "protspaceVersion": "4.15.0",
      "gitSha": "621ea942223ad487fcb7418022d9a3fd17acaf39",
      "command": "build_showcase.py build --only swissprot --cli-root $CLI",
      "builtAt": "2026-09-30T21:56:02+00:00",
      "zenodoDoi": null
    }
  }
};
