// GENERATED by apps/protspace/scripts/generate_examples/write_manifest.py; do not edit.
// Every value below is read from the bundle file it describes. To change it, rebuild
// the bundle and rerun the writer (its docstring shows how).

/** Where a bundle's file is served from and what it holds. */
interface ExampleBundleRecord {
  /** Path under `apps/web/public/` for `'repo'`; the release asset name for `'release'`. */
  readonly file: string;
  /** `'repo'`: committed under `apps/web/public/`. `'release'`: an asset of `release`, deployed under `examples/`. */
  readonly hosting: 'repo' | 'release';
  /** Decoded file size in bytes (download progress is measured against it). */
  readonly bytes: number;
  readonly sha256: string;
  readonly proteins: number;
  /** Annotation columns, in file order, without the protein-id column. */
  readonly columns: readonly string[];
  /** Projection names, in file order. */
  readonly projections: readonly string[];
  /** Whether the bundle carries a statistics part (separation scores, from `protspace stats`). */
  readonly statistics: boolean;
  readonly releases: {
    /** UniProt release the protein set was drawn from. */
    readonly membership: string | null;
    /** Release per annotation column group, e.g. `{ uniprot: '2026_03' }`. */
    readonly annotations: Readonly<Record<string, string>>;
  };
  readonly protspaceVersion: string | null;
  readonly gitSha: string | null;
  readonly command: string | null;
  readonly builtAt: string | null;
  readonly zenodoDoi: string | null;
}

/** A file of the previous release, still deployed for one cycle so open tabs and old links keep working. */
interface RetainedBundle {
  readonly release: string;
  readonly file: string;
  readonly bytes: number;
  readonly sha256: string;
}

interface ExampleManifest {
  /** The GitHub release the `'release'`-hosted files come from; `null` while every file is in the repository. */
  readonly release: string | null;
  readonly retained: readonly RetainedBundle[];
  readonly examples: Readonly<Record<string, ExampleBundleRecord>>;
}

export const EXAMPLE_MANIFEST: ExampleManifest = {
  "release": "showcase-2026_03",
  "retained": [],
  "examples": {
    "demo": {
      "file": "data.parquetbundle",
      "hosting": "repo",
      "bytes": 957284,
      "sha256": "ab291e05e149646a5e3bbe62019584f62d98cc35ec59abc7cd6e1caad78b22b1",
      "proteins": 7831,
      "columns": [
        "protein_families",
        "annotation_score",
        "cc_subcellular_location",
        "ec",
        "fragment",
        "go_bp",
        "go_cc",
        "go_mf",
        "keyword",
        "length",
        "protein_existence",
        "reviewed",
        "xref_pdb",
        "root",
        "domain",
        "kingdom",
        "phylum",
        "class",
        "order",
        "family",
        "genus",
        "species",
        "pfam",
        "superfamily",
        "cath",
        "signal_peptide",
        "smart",
        "cdd",
        "panther",
        "prosite",
        "prints",
        "pfam_clan",
        "ted_domains",
        "predicted_subcellular_location",
        "predicted_membrane",
        "predicted_signal_peptide",
        "predicted_transmembrane",
        "gene_name",
        "protein_name",
        "uniprot_kb_id"
      ],
      "projections": [
        "ProtT5 — UMAP 2",
        "ProtT5 — PCA 2",
        "ESM2-650M — UMAP 2",
        "ESM2-650M — PCA 2"
      ],
      "statistics": false,
      "releases": {
        "membership": "2026_01",
        "annotations": {
          "refreshed": "2026_03",
          "source": "2026_01"
        }
      },
      "protspaceVersion": "4.16.0",
      "gitSha": "b5f324f8b3d380dfc90ddf35469d4ac293d83427",
      "command": "build_showcase.py build --only demo --cli-root $CLI",
      "builtAt": "2026-10-02T22:23:18+00:00",
      "zenodoDoi": null
    },
    "three-finger-toxins": {
      "file": "three-finger-toxins_2026_03_v3.parquetbundle",
      "hosting": "release",
      "bytes": 141224,
      "sha256": "5ac49490ec10831c03babfea8f9d7a42d21cc171c9626476778b3d70bacbcfe8",
      "proteins": 1089,
      "columns": [
        "toxin_class",
        "toxin_subfamily",
        "eat_split",
        "toxin_class_withheld",
        "toxin_subfamily_withheld",
        "toxin_class_uniprot_rule",
        "species",
        "genus",
        "family",
        "protein_families",
        "reviewed",
        "length",
        "fragment",
        "protein_existence",
        "annotation_score",
        "keyword",
        "xref_pdb",
        "go_bp",
        "go_mf",
        "pfam",
        "signal_peptide",
        "panther",
        "prosite",
        "ted_domains",
        "predicted_subcellular_location",
        "predicted_membrane",
        "predicted_signal_peptide",
        "gene_name",
        "protein_name",
        "uniprot_kb_id",
        "mature_length",
        "toxin_class__pred_value",
        "toxin_class__pred_confidence",
        "toxin_class__pred_source",
        "toxin_subfamily__pred_value",
        "toxin_subfamily__pred_confidence",
        "toxin_subfamily__pred_source",
        "cluster_elbow_ProtT5 — UMAP 2",
        "cluster_silhouette_ProtT5 — UMAP 2",
        "cluster_elbow_ProtT5 — PCA 2",
        "cluster_silhouette_ProtT5 — PCA 2"
      ],
      "projections": [
        "ProtT5 — UMAP 2",
        "ProtT5 — PCA 2"
      ],
      "statistics": true,
      "releases": {
        "membership": "2026_03",
        "annotations": {
          "refreshed": "2026_03",
          "withheld-truth": "2026_03"
        }
      },
      "protspaceVersion": "4.16.0",
      "gitSha": "b5f324f8b3d380dfc90ddf35469d4ac293d83427",
      "command": "build_showcase.py build --only three-finger-toxins --cli-root $CLI",
      "builtAt": "2026-10-02T22:23:12+00:00",
      "zenodoDoi": null
    },
    "human-fly": {
      "file": "human-fly_2026_03_v3.parquetbundle",
      "hosting": "release",
      "bytes": 16055099,
      "sha256": "a2fe8de232d976087564b4d1239928518e0e9e074444d809e8484151bf0bb558",
      "proteins": 105562,
      "columns": [
        "species",
        "protein_families",
        "annotation_score",
        "cc_subcellular_location",
        "ec",
        "fragment",
        "go_bp",
        "go_cc",
        "go_mf",
        "keyword",
        "length",
        "protein_existence",
        "reviewed",
        "xref_pdb",
        "root",
        "domain",
        "kingdom",
        "phylum",
        "class",
        "order",
        "family",
        "genus",
        "pfam",
        "superfamily",
        "cath",
        "signal_peptide",
        "smart",
        "cdd",
        "panther",
        "prosite",
        "prints",
        "pfam_clan",
        "ted_domains",
        "gene_name",
        "protein_name",
        "uniprot_kb_id",
        "cluster_elbow_ProtT5 — UMAP 2",
        "cluster_silhouette_ProtT5 — UMAP 2",
        "cluster_elbow_ProtT5 — PCA 2",
        "cluster_silhouette_ProtT5 — PCA 2"
      ],
      "projections": [
        "ProtT5 — UMAP 2",
        "ProtT5 — PCA 2"
      ],
      "statistics": true,
      "releases": {
        "membership": "2025_04",
        "annotations": {
          "refreshed": "2026_03"
        }
      },
      "protspaceVersion": "4.16.0",
      "gitSha": "b5f324f8b3d380dfc90ddf35469d4ac293d83427",
      "command": "build_showcase.py build --only human-fly --cli-root $CLI",
      "builtAt": "2026-10-02T22:35:18+00:00",
      "zenodoDoi": null
    },
    "beta-lactamase": {
      "file": "beta-lactamase_2026_03_v3.parquetbundle",
      "hosting": "release",
      "bytes": 13308868,
      "sha256": "3bc6df0e901e6cd93f8464f470d1169f5524f91d3304b799cb06653ef5b3af06",
      "proteins": 113015,
      "columns": [
        "protein_families",
        "annotation_score",
        "cc_subcellular_location",
        "ec",
        "fragment",
        "go_bp",
        "go_cc",
        "go_mf",
        "keyword",
        "length",
        "protein_existence",
        "reviewed",
        "xref_pdb",
        "root",
        "domain",
        "kingdom",
        "phylum",
        "class",
        "order",
        "family",
        "genus",
        "species",
        "pfam",
        "superfamily",
        "cath",
        "signal_peptide",
        "smart",
        "cdd",
        "panther",
        "prosite",
        "prints",
        "pfam_clan",
        "ted_domains",
        "gene_name",
        "protein_name",
        "uniprot_kb_id",
        "cluster_elbow_ProtT5 — UMAP 2",
        "cluster_silhouette_ProtT5 — UMAP 2",
        "cluster_elbow_ProtT5 — PCA 2",
        "cluster_silhouette_ProtT5 — PCA 2"
      ],
      "projections": [
        "ProtT5 — UMAP 2",
        "ProtT5 — PCA 2"
      ],
      "statistics": true,
      "releases": {
        "membership": "2026_02",
        "annotations": {
          "refreshed": "2026_03"
        }
      },
      "protspaceVersion": "4.16.0",
      "gitSha": "b5f324f8b3d380dfc90ddf35469d4ac293d83427",
      "command": "build_showcase.py build --only beta-lactamase --cli-root $CLI",
      "builtAt": "2026-10-02T22:25:04+00:00",
      "zenodoDoi": null
    },
    "swissprot": {
      "file": "swissprot_2026_03_v3.parquetbundle",
      "hosting": "release",
      "bytes": 87783085,
      "sha256": "a566bacf207d3c5f2b4afcbad23660ba7b52bc4a12894654565ea6325cc407b3",
      "proteins": 573649,
      "columns": [
        "domain",
        "annotation_score",
        "cc_subcellular_location",
        "ec",
        "fragment",
        "go_bp",
        "go_cc",
        "go_mf",
        "keyword",
        "length",
        "protein_existence",
        "protein_families",
        "reviewed",
        "xref_pdb",
        "root",
        "kingdom",
        "phylum",
        "class",
        "order",
        "family",
        "genus",
        "species",
        "pfam",
        "superfamily",
        "cath",
        "signal_peptide",
        "smart",
        "cdd",
        "panther",
        "prosite",
        "prints",
        "pfam_clan",
        "ted_domains",
        "gene_name",
        "protein_name",
        "uniprot_kb_id",
        "cluster_elbow_ProtT5 — UMAP 2",
        "cluster_silhouette_ProtT5 — UMAP 2",
        "cluster_elbow_ProtT5 — PCA 2",
        "cluster_silhouette_ProtT5 — PCA 2"
      ],
      "projections": [
        "ProtT5 — UMAP 2",
        "ProtT5 — PCA 2"
      ],
      "statistics": true,
      "releases": {
        "membership": "2025_04",
        "annotations": {
          "refreshed": "2026_03"
        }
      },
      "protspaceVersion": "4.16.0",
      "gitSha": "b5f324f8b3d380dfc90ddf35469d4ac293d83427",
      "command": "build_showcase.py build --only swissprot --cli-root $CLI",
      "builtAt": "2026-10-02T22:29:29+00:00",
      "zenodoDoi": null
    }
  }
};
