// GENERATED by apps/protspace/scripts/generate_examples/write_manifest.py; do not edit.
// Every value below is read from the bundle file it describes. To change it, rebuild
// the bundle and rerun the writer (its docstring shows how).

/** Where a bundle's file is served from and what it holds. */
interface ExampleBundleRecord {
  /** Path under `apps/web/public/` for `'repo'`; the release asset name for `'release'`. */
  readonly file: string;
  /** `'repo'`: committed under `apps/web/public/`. `'release'`: an asset of `release`, deployed under `examples/`. */
  readonly hosting: 'repo' | 'release';
  /** Decoded file size in bytes (download progress is measured against it). */
  readonly bytes: number;
  readonly sha256: string;
  readonly proteins: number;
  /** Annotation columns, in file order, without the protein-id column. */
  readonly columns: readonly string[];
  /** Projection names, in file order. */
  readonly projections: readonly string[];
  readonly releases: {
    /** UniProt release the protein set was drawn from. */
    readonly membership: string | null;
    /** Release per annotation column group, e.g. `{ uniprot: '2026_03' }`. */
    readonly annotations: Readonly<Record<string, string>>;
  };
  readonly protspaceVersion: string | null;
  readonly gitSha: string | null;
  readonly command: string | null;
  readonly builtAt: string | null;
  readonly zenodoDoi: string | null;
}

/** A file of the previous release, still deployed for one cycle so open tabs and old links keep working. */
interface RetainedBundle {
  readonly release: string;
  readonly file: string;
  readonly bytes: number;
  readonly sha256: string;
}

interface ExampleManifest {
  /** The GitHub release the `'release'`-hosted files come from; `null` while every file is in the repository. */
  readonly release: string | null;
  readonly retained: readonly RetainedBundle[];
  readonly examples: Readonly<Record<string, ExampleBundleRecord>>;
}

export const EXAMPLE_MANIFEST: ExampleManifest = {
  "release": null,
  "retained": [],
  "examples": {
    "demo": {
      "file": "data.parquetbundle",
      "hosting": "repo",
      "bytes": 865499,
      "sha256": "dcebba0f1ca15b49a44ebacd2a0807b2e7b528d51efb84de7a8c8a6ba27770fb",
      "proteins": 7831,
      "columns": [
        "protein_families",
        "ec",
        "keyword",
        "length",
        "reviewed",
        "cath",
        "pfam",
        "superfamily",
        "phylum",
        "class",
        "order",
        "family",
        "genus",
        "species",
        "gene_name",
        "protein_name",
        "uniprot_kb_id"
      ],
      "projections": [
        "ProtT5 — UMAP 2",
        "ProtT5 — PCA 2",
        "ESM2-650M — UMAP 2",
        "ESM2-650M — PCA 2"
      ],
      "releases": {
        "membership": null,
        "annotations": {}
      },
      "protspaceVersion": null,
      "gitSha": null,
      "command": null,
      "builtAt": null,
      "zenodoDoi": null
    },
    "venom_eat_stats": {
      "file": "data/venom_eat_stats.parquetbundle",
      "hosting": "repo",
      "bytes": 201687,
      "sha256": "75124338953565bdb394f110be54b6f29e35099536cafc15d9d359aad51bfb31",
      "proteins": 811,
      "columns": [
        "annotation_score",
        "cc_subcellular_location",
        "ec",
        "fragment",
        "gene_name",
        "go_bp",
        "go_cc",
        "go_mf",
        "keyword",
        "length",
        "organism_id",
        "protein_name",
        "protein_existence",
        "protein_families",
        "reviewed",
        "sequence",
        "uniprot_kb_id",
        "xref_pdb",
        "root",
        "domain",
        "kingdom",
        "phylum",
        "class",
        "order",
        "family",
        "genus",
        "species",
        "cluster_elbow_ProtT5 — PCA 2",
        "cluster_silhouette_ProtT5 — PCA 2",
        "cluster_elbow_ProtT5 — UMAP 2",
        "cluster_silhouette_ProtT5 — UMAP 2",
        "ec__pred_value",
        "ec__pred_confidence",
        "ec__pred_source",
        "protein_families__pred_value",
        "protein_families__pred_confidence",
        "protein_families__pred_source"
      ],
      "projections": [
        "ProtT5 — PCA 2",
        "ProtT5 — UMAP 2"
      ],
      "releases": {
        "membership": null,
        "annotations": {}
      },
      "protspaceVersion": null,
      "gitSha": null,
      "command": null,
      "builtAt": null,
      "zenodoDoi": null
    },
    "phosphatase": {
      "file": "data/phosphatase.parquetbundle",
      "hosting": "repo",
      "bytes": 434341,
      "sha256": "b10d2d625ec2bffedc7b49674179a0c5d01a9da4c70762eb8ae78deb13b2f13c",
      "proteins": 1587,
      "columns": [
        "annotation_score",
        "cc_subcellular_location",
        "ec",
        "fragment",
        "go_bp",
        "go_cc",
        "go_mf",
        "keyword",
        "length",
        "protein_existence",
        "protein_families",
        "reviewed",
        "xref_pdb",
        "root",
        "domain",
        "kingdom",
        "phylum",
        "class",
        "order",
        "family",
        "genus",
        "species",
        "pfam",
        "superfamily",
        "cath",
        "signal_peptide",
        "smart",
        "cdd",
        "panther",
        "prosite",
        "prints",
        "pfam_clan",
        "ted_domains",
        "predicted_subcellular_location",
        "predicted_membrane",
        "predicted_signal_peptide",
        "predicted_transmembrane",
        "gene_name",
        "protein_name",
        "uniprot_kb_id"
      ],
      "projections": [
        "ESM2-650M — PCA 2",
        "ESM2-650M — UMAP 2"
      ],
      "releases": {
        "membership": null,
        "annotations": {}
      },
      "protspaceVersion": null,
      "gitSha": null,
      "command": null,
      "builtAt": null,
      "zenodoDoi": null
    },
    "5K": {
      "file": "data/5K.parquetbundle",
      "hosting": "repo",
      "bytes": 244359,
      "sha256": "324d3d50db8ed94d4b414da971c9c944620ac1a4fbe45a192e5f6031ef0b2078",
      "proteins": 5181,
      "columns": [
        "phylum",
        "protein_existence",
        "length_fixed",
        "length_quantile"
      ],
      "projections": [
        "PCA_2",
        "PCA_3"
      ],
      "releases": {
        "membership": null,
        "annotations": {}
      },
      "protspaceVersion": null,
      "gitSha": null,
      "command": null,
      "builtAt": null,
      "zenodoDoi": null
    },
    "7K_toxprot": {
      "file": "data/7K_toxprot.parquetbundle",
      "hosting": "repo",
      "bytes": 576771,
      "sha256": "1f577a89475c86187c842ff4b2ca0ab54bef0d1afd7b436e334f0930d8a9a9d7",
      "proteins": 7445,
      "columns": [
        "annotation_score",
        "cc_subcellular_location",
        "fragment",
        "gene_name",
        "protein_name",
        "protein_existence",
        "protein_families",
        "reviewed",
        "uniprot_kb_id",
        "xref_pdb",
        "root",
        "domain",
        "kingdom",
        "phylum",
        "class",
        "order",
        "family",
        "genus",
        "species",
        "pfam",
        "superfamily",
        "cath",
        "signal_peptide",
        "length_fixed",
        "length_quantile"
      ],
      "projections": [
        "PCA_2",
        "UMAP_2"
      ],
      "releases": {
        "membership": null,
        "annotations": {}
      },
      "protspaceVersion": null,
      "gitSha": null,
      "command": null,
      "builtAt": null,
      "zenodoDoi": null
    },
    "35K_ec_brenda": {
      "file": "data/35K_ec_brenda.parquetbundle",
      "hosting": "repo",
      "bytes": 4487626,
      "sha256": "abdd5a71a3613a5ef644c25a39a98ca32ee1fabc15d6c27f99f59dee21662109",
      "proteins": 35077,
      "columns": [
        "annotation_score",
        "cc_subcellular_location",
        "fragment",
        "gene_name",
        "protein_name",
        "protein_existence",
        "protein_families",
        "reviewed",
        "uniprot_kb_id",
        "xref_pdb",
        "root",
        "domain",
        "kingdom",
        "phylum",
        "class",
        "order",
        "family",
        "genus",
        "species",
        "pfam",
        "superfamily",
        "cath",
        "signal_peptide",
        "length_fixed",
        "length_quantile"
      ],
      "projections": [
        "PCA_2",
        "UMAP_2"
      ],
      "releases": {
        "membership": null,
        "annotations": {}
      },
      "protspaceVersion": null,
      "gitSha": null,
      "command": null,
      "builtAt": null,
      "zenodoDoi": null
    },
    "beta_lactamase_ec": {
      "file": "data/beta_lactamase_ec.parquetbundle",
      "hosting": "repo",
      "bytes": 2084334,
      "sha256": "737f185f68b809c75767877bbe438a9f43f60bea5340f46295c6ff99e70a700f",
      "proteins": 35504,
      "columns": [
        "annotation_score",
        "cc_subcellular_location",
        "fragment",
        "protein_existence",
        "protein_families",
        "reviewed",
        "xref_pdb",
        "root",
        "domain",
        "kingdom",
        "phylum",
        "class",
        "order",
        "family",
        "genus",
        "species",
        "pfam",
        "superfamily",
        "cath",
        "signal_peptide",
        "length_fixed",
        "length_quantile"
      ],
      "projections": [
        "PCA_2",
        "UMAP_2"
      ],
      "releases": {
        "membership": null,
        "annotations": {}
      },
      "protspaceVersion": null,
      "gitSha": null,
      "command": null,
      "builtAt": null,
      "zenodoDoi": null
    },
    "40K": {
      "file": "data/40K.parquetbundle",
      "hosting": "repo",
      "bytes": 1843827,
      "sha256": "4c280676974d01d28f7c1d2d5c9369630a3e7f4255b6d0b200bc21d0c7ac0ef4",
      "proteins": 40026,
      "columns": [
        "protein_existence",
        "length_fixed",
        "length_quantile",
        "pfam",
        "cath",
        "superfamily",
        "signal_peptide"
      ],
      "projections": [
        "PCA_2",
        "PCA_3"
      ],
      "releases": {
        "membership": null,
        "annotations": {}
      },
      "protspaceVersion": null,
      "gitSha": null,
      "command": null,
      "builtAt": null,
      "zenodoDoi": null
    },
    "105K_homoSapiens_drosophilaMelanogaster": {
      "file": "data/105K_homoSapiens_drosophilaMelanogaster.parquetbundle",
      "hosting": "repo",
      "bytes": 10109361,
      "sha256": "506383a0576f8dc7085f527f951209cfc365896be7b5c6bff7f51c160e66205b",
      "proteins": 105562,
      "columns": [
        "annotation_score",
        "cc_subcellular_location",
        "fragment",
        "gene_name",
        "protein_name",
        "protein_existence",
        "protein_families",
        "reviewed",
        "uniprot_kb_id",
        "xref_pdb",
        "root",
        "domain",
        "kingdom",
        "phylum",
        "class",
        "order",
        "family",
        "genus",
        "species",
        "pfam",
        "superfamily",
        "cath",
        "signal_peptide",
        "length_fixed",
        "length_quantile"
      ],
      "projections": [
        "UMAP_2",
        "PCA_2"
      ],
      "releases": {
        "membership": null,
        "annotations": {}
      },
      "protspaceVersion": null,
      "gitSha": null,
      "command": null,
      "builtAt": null,
      "zenodoDoi": null
    },
    "127K_beta_lactamase": {
      "file": "data/127K_beta_lactamase.parquetbundle",
      "hosting": "repo",
      "bytes": 8717148,
      "sha256": "8f95df5bc645da631015819dce4822ff81d2f7c29bf3b3d320905ac23c23264f",
      "proteins": 127115,
      "columns": [
        "annotation_score",
        "cc_subcellular_location",
        "fragment",
        "gene_name",
        "protein_name",
        "protein_existence",
        "protein_families",
        "reviewed",
        "uniprot_kb_id",
        "xref_pdb",
        "root",
        "domain",
        "kingdom",
        "phylum",
        "class",
        "order",
        "family",
        "genus",
        "species",
        "length_fixed",
        "length_quantile"
      ],
      "projections": [
        "PCA_2",
        "UMAP_2"
      ],
      "releases": {
        "membership": null,
        "annotations": {}
      },
      "protspaceVersion": null,
      "gitSha": null,
      "command": null,
      "builtAt": null,
      "zenodoDoi": null
    },
    "beta_lactamase_pn": {
      "file": "data/beta_lactamase_pn.parquetbundle",
      "hosting": "repo",
      "bytes": 12210217,
      "sha256": "fbb6a096ecc979ece5bccd1284797d662e18c81d96fca4f27e12ad98f7ef02a9",
      "proteins": 248482,
      "columns": [
        "annotation_score",
        "cc_subcellular_location",
        "fragment",
        "protein_existence",
        "protein_families",
        "reviewed",
        "xref_pdb",
        "root",
        "domain",
        "kingdom",
        "phylum",
        "class",
        "order",
        "family",
        "genus",
        "species",
        "length_fixed",
        "length_quantile"
      ],
      "projections": [
        "PCA_2",
        "UMAP_2"
      ],
      "releases": {
        "membership": null,
        "annotations": {}
      },
      "protspaceVersion": null,
      "gitSha": null,
      "command": null,
      "builtAt": null,
      "zenodoDoi": null
    }
  }
};
