name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
        id-token: write
        contents: write
    environment:
      name: pypi
      url: https://pypi.org/p/protspace

    steps:
      - name: Setup | Checkout Repository at workflow sha
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}

      - name: Setup | Force correct release branch on workflow sha
        run: |
          git checkout -B ${{ github.ref_name }} ${{ github.sha }}

      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@v9.11.1
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            git_committer_name: "github-actions"
            git_committer_email: "actions@users.noreply.github.com"
            build: false
            changelog: true
            commit: true
            push: true
            tag: true
            vcs_release: true

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
            enable-cache: true
            cache-dependency-glob: "uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
    
      - name: Build Python
        run: uv build

      - name: Publish | Upload package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: steps.release.outputs.released == 'true'

      - name: Publish | Upload to GitHub Release Assets
        uses: python-semantic-release/publish-action@v9.8.9
        if: steps.release.outputs.released == 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.release.outputs.tag }}