name: Python Build Workflow

on:
  repository_dispatch:
    types: [trigger-python-build]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/protspace
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: v${{ github.event.client_payload.version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Build Python Package
        run: uv build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Publish to GitHub Release Assets
        uses: python-semantic-release/publish-action@v9.8.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ github.event.client_payload.version }}