name: Python Build Workflow

on:
  repository_dispatch:
    types: [trigger-python-build]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/protspace
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.tag }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Cache Python Semantic Release
        uses: actions/cache@v3
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-semantic-release-v9.11.1
          restore-keys: |
            ${{ runner.os }}-uv-semantic-release-

      - name: Install Python Semantic Release
        run: uv tool install python-semantic-release@v9.11.1

      - name: Build Python Package
        run: uv build
    
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Publish to GitHub Release
        run: uv tool run semantic-release publish --tag ${{ github.event.client_payload.tag }}
        