name: Python Build Workflow

on:
  repository_dispatch:
    types: [trigger-python-build]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/protspace
    env:
        UV_TOOL_DIR: /tmp/.uv-tools
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.client_payload.tag }}

      - name: Force correct release branch
        run: |
          git checkout -B ${{ github.ref_name }} ${{ github.event.client_payload.tag }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Restore uv tools
        uses: actions/cache@v4
        with:
            path: /tmp/.uv-tools
            key: uv-tools-${{ runner.os }}-psr-v9.11.1
            restore-keys: |
              uv-tools-${{ runner.os }}-psr-v9.11.1
              uv-tools-${{ runner.os }}  

      - name: Install Python Semantic Release
        run: uv tool install python-semantic-release@v9.11.1
        
      - name: Build Python Package
        run: uv build
    
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Publish to GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: uv tool run --from python-semantic-release semantic-release publish --tag ${{ github.event.client_payload.tag }}
        